---
api:                2

# Basic Drush Make file for Drupal. Be sure to update the drupal_major_version
# variable inside config.yml if you change the major version in this file.

# Drupal core (major version, e.g. 6.x, 7.x, 8.x).
core:               "7.x"

defaults:
  projects:
    subdir:         "contrib"
    version:        ~

projects:

  # Core.
  drupal:
    version:        "7.59"
    # Use this if you need a working git repository of Drupal core instead of
    # the latest stable.
    # type:         "core"
    # download:
    #   # Drupal core branch (e.g. "6.x", "7.x", "8.3.x", "8.5.x").
    #   branch:     "8.4.x"
    #   working-copy: true

  # Profile.
  govcms:
    # version:      "2.20"
    type:           "profile"
    subdir:         ""
    download:
      type:         "git"
      url:          "https://github.com/govCMS/govCMS.git"
      branch:       "7.x-2.x"
      working-copy: true

  # Other modules.
  devel:
    subdir:         "development"
